---
- hosts: all
  become: true
  pre_tasks:

  - name: Install updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    changed_when: false

- hosts: Ubuntu
  become: true
  roles:
    - NTP
    - OpenStack
    - SQL
    - MessageQ
    - memcached
    - ETCD
